### PR TITLE
Hotfix/allow feed ptr meta var

### LINKED ISSUE #35: Add the ability to configure feeds for records up filter
### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
- ns1_record
- ns1_datafeed

### Terraform Configuration Files
```hcl
resource "ns1_datafeed" "api" {
  name      = "${ns1_record.primary_api.domain}"
  source_id = "${module.notification_list.datasource_ns1_monitoring}"

  config = {
    jobid = "${ns1_monitoringjob.api.id}"
  }
}

resource "ns1_record" "api" {
  zone   = "${ns1_zone.example_com.zone}"
  domain = "api.${ns1_zone.example_com.zone}"
  type   = "CNAME"
  ttl    = 900

  answers = [
    {
      answer = "${ns1_record.primary_api.domain}"

      meta = {
        priority = 0
        up       = true
      }
    },
    {
      answer = "${ns1_record.secondary_api.domain}"

      meta = {
        priority = 1
        up       = true
      }
    },
  ]

  filters = {
    filter = "up"
  }

  filters = {
    filter = "priority"
  }
}
```

### Expected Behavior
This configuration works find but I'd like to be able configure it as the following
```hcl
  answers = [
    {
      answer = "${ns1_record.primary_api.domain}"

     feeds = [
                {
                    feed = "${ns1_datafeed.api.id}"
                    source = "${module.notification_list.datasource_ns1_monitoring}"
                }
            ],

      meta = {
        priority = 0
        up       = {
          feed = "${ns1_datafeed.api.id}"
         }
      }
    },
    {
      answer = "${ns1_record.secondary_api.domain}"

      meta = {
        priority = 1
        up       = true
      }
    },
  ]
```

### Actual Behavior
Maybe there is another option to get this. I'd like to hear that

### References
When adding the feeds manually from NS1 portal, im getting the same crash as GH-31 mentioned

Thanks

### PR DESCRIPTION
**Pull request by mburtless**
Allows raw json for a feed pointer to be used as a value for a metadata key, which in turn enables a feed pointer to be generated when the caller generating the input does not have the ability to create new FeedPtr objects.

This is required to resolve https://github.com/terraform-providers/terraform-provider-ns1/issues/35 and enable a workaround to use feed pointers as metadata values via Terraform.

This PR also disables default behavior of casting all values for the `up` metadata key that != 1 as `false`.  This enables using a feed pointer as a value for `up` and also prepares for Terraform 0.12, in which string conversions of boolean configuration values will no longer be automatically converted to `1` or `0` (See https://github.com/hashicorp/terraform/issues/19618 for more info).

This PR is based on a fork by @glennslaven, a big thanks is owed for his contribution!

### CODE REVIEW

**Comment by ionigman** [comment]
Tested placing meta/feeds into answers and records. Both work fine. Removal also works fine.

File: rest/model/data/meta.go [hunk 1]
```diff
@@ -179,6 +179,13 @@ func FormatInterface(i interface{}) string {
 			slc = append(slc, s.(string))
 		}
 		return strings.Join(slc, ",")
+	case map[string]interface{}:
+		// Required for Terraform workaround to allow users to submit raw json of feed pointer
+		// as value for metadata.  See https://github.com/terraform-providers/terraform-provider-ns1/issues/35
+		mapVal := i.(map[string]interface{})
```
Comment (supernomad) [inline rest/model/data/meta.go]: isn't this just the `v` value from above? or is there a reason you are "recasting" `i` here?

**Review by supernomad — COMMENTED** [review]
quick question

File: rest/model/data/meta.go [hunk 2]
```diff
@@ -179,6 +179,13 @@ func FormatInterface(i interface{}) string {
...
+		feedPtr := FeedPtr{FeedID: mapVal["feed"].(string)}
```
Comment (supernomad) [inline rest/model/data/meta.go]: do we need to ensure `mapVal["feed"]` actually exists before casting here? Or is it just assumed that the "feed" key will always exist?

File: rest/model/data/meta.go (hunk 1 above)
Comment (mburtless) [reply rest/model/data/meta.go]: Good catch, no reason to recast

File: rest/model/data/meta.go (hunk 2 above)
Comment (mburtless) [reply rest/model/data/meta.go]: It was assumed, but we should definitely ensure it exists as no other key is valid.  Rewrote the case so it will panic if a `map[string]interface{}` is passed with any key other than `feed`, as that's the only valid value for this use case.

**Review by supernomad — APPROVED** [review]
:rocket:
